language: objective-c
osx_image: xcode7.3

env:
  - >
    xcode_project=Gaikan.xcodeproj
    xcode_scheme=Gaikan
    xcode_sdk=iphonesimulator
    xcode_platform="platform=iOS Simulator,name=iPhone 6"

before_install:
  - brew update
  - brew install carthage

install: carthage update --platform iOS

script:
  - >
    set -o pipefail && xcodebuild
    -project ${xcode_project}
    -scheme ${xcode_scheme}
    -sdk ${xcode_sdk}
    -destination "${xcode_platform}" test | xcpretty -c

branches:
  except:
    - /^tags.+/
